import type { TripWithDetails } from '@/types';

export const fallbackTrips: TripWithDetails[] = [
  {
    id: '11111111-1111-1111-1111-111111111111',
    title: 'Youth Camp',
    slug: 'youth-camp',
    duration: '4.5 days',
    difficulty: 'Beginner (Class I–II+)',
    age_range: '10–16',
    price: 125000,
    description:
      'Camp and paddle for four and a half days on the beautiful Trinity River! Students build whitewater paddling skills on Class I–II+ rapids while creating new relationships with the outdoors: swimming, camping, and playing in nature. Through guided on-water and on-shore experiences, T.R.I.K.S. aims to nurture future stewards of the river and the outdoors.',
    short_description:
      'Camp and paddle for four and a half days on the beautiful Trinity River! Build whitewater skills on Class I–II+ rapids while camping under the stars.',
    includes: [
      'All kayaking gear (kayak, paddle, PFD, helmet, spray skirt, wetsuit)',
      'Professional instruction',
      'Camping (paid-for sites)',
      'Meals',
    ],
    location: 'Hayden Flat Campground, Trinity River',
    image_url: '/images/youth-camp-thumbnail.jpg',
    gallery_urls: [
      '/images/youth-camp-gallery.jpg',
      '/images/youth-camp-thumbnail.jpg',
    ],
    video_url: null,
    is_featured: true,
    created_at: '',
    itinerary_days: [
      {
        id: 'd0',
        trip_id: '11111111-1111-1111-1111-111111111111',
        day_number: 0.5,
        title: 'Arrival & Camp Setup',
        description: 'Student drop-off, camp setup, gear & kayak outfitting, camp orientation, and games.',
        river_section: 'Hayden Flat Campground',
        miles: null,
        activities_am: '',
        activities_pm: 'Student drop-off (3–4 PM), camp setup, gear & kayak outfitting, camp orientation, games.',
      },
      {
        id: 'd1',
        trip_id: '11111111-1111-1111-1111-111111111111',
        day_number: 1,
        title: 'Wet Exit & Flatwater Paddling',
        description: 'Build water comfort and learn essential safety skills at Hayden Flat.',
        river_section: 'Hayden Flat',
        miles: 0,
        activities_am: 'Water comfort, safety briefing, swimming, wet exit progression (no skirt → skirt → full wet exit).',
        activities_pm: 'Intro paddles, flatwater paddling, on-water games.',
      },
      {
        id: 'd2',
        trip_id: '11111111-1111-1111-1111-111111111111',
        day_number: 2,
        title: 'Downstream! Class I',
        description: 'First downstream paddle — French Creek to Hayden Flat.',
        river_section: 'French Creek to Hayden Flat',
        miles: 4,
        activities_am: '',
        activities_pm: '',
      },
      {
        id: 'd3',
        trip_id: '11111111-1111-1111-1111-111111111111',
        day_number: 3,
        title: 'Downstream!',
        description: 'Longer stretch — Big Bar to French Creek.',
        river_section: 'Big Bar to French Creek',
        miles: 5,
        activities_am: '',
        activities_pm: '',
      },
      {
        id: 'd4',
        trip_id: '11111111-1111-1111-1111-111111111111',
        day_number: 4,
        title: 'Final Downstream Day!',
        description: 'Final day of moving downstream with two route options.',
        river_section: '',
        miles: 7,
        activities_am: 'Warm-up, paddle downstream.',
        activities_pm: 'Paddle to takeout, check-out gear, student pick-up.',
      },
    ],
    trip_dates: [
      {
        id: 'td1',
        trip_id: '11111111-1111-1111-1111-111111111111',
        start_date: '2026-07-05',
        end_date: '2026-07-09',
        max_participants: 8,
        current_participants: 0,
        is_available: true,
      },
    ],
  },
  {
    id: '22222222-2222-2222-2222-222222222222',
    title: 'Youth Clinic (Day Program)',
    slug: 'youth-clinic',
    duration: '4 days',
    difficulty: 'Beginner (Class I–II+)',
    age_range: '10–16',
    price: null,
    description:
      'A 4-day clinic offered at a lower price to locals from Humboldt and Trinity counties. While T.R.I.K.S. doesn\'t provide camping and meals, we encourage families to gather at central camping areas to promote togetherness. Same on-water curriculum as Youth Camp.',
    short_description:
      'A 4-day clinic for local youth. Same on-water curriculum as Youth Camp, without camping — perfect for families in Humboldt and Trinity counties.',
    includes: ['All kayaking gear', 'Professional instruction', 'Lunch'],
    location: 'Hayden Flat Campground area, Trinity River',
    image_url: '/images/youth-clinic-thumbnail.jpg',
    gallery_urls: [
      '/images/youth-clinic-gallery.jpg',
      '/images/youth-clinic-thumbnail.jpg',
    ],
    video_url: null,
    is_featured: true,
    created_at: '',
    itinerary_days: [
      {
        id: 'yc1',
        trip_id: '22222222-2222-2222-2222-222222222222',
        day_number: 1,
        title: 'Wet Exit & Flatwater Paddling',
        description: 'Build water comfort and learn essential safety skills at Hayden Flat.',
        river_section: 'Hayden Flat',
        miles: 0,
        activities_am: 'Water comfort, safety briefing, swimming, wet exit progression.',
        activities_pm: 'Intro paddles, flatwater paddling, on-water games.',
      },
      {
        id: 'yc2',
        trip_id: '22222222-2222-2222-2222-222222222222',
        day_number: 2,
        title: 'Downstream!',
        description: 'French Creek to Hayden Flat.',
        river_section: 'French Creek to Hayden Flat',
        miles: 4,
        activities_am: 'Flatwater warm-up, paddle downstream.',
        activities_pm: 'Paddle to Hayden, on-water games.',
      },
      {
        id: 'yc3',
        trip_id: '22222222-2222-2222-2222-222222222222',
        day_number: 3,
        title: 'Downstream!',
        description: 'Big Bar to French Creek.',
        river_section: 'Big Bar to French Creek',
        miles: 5,
        activities_am: 'Flatwater warm-up, paddle downstream.',
        activities_pm: 'Paddle to take-out.',
      },
      {
        id: 'yc4',
        trip_id: '22222222-2222-2222-2222-222222222222',
        day_number: 4,
        title: 'Final Downstream Day!',
        description: 'Final day with two route options.',
        river_section: 'Bagdad to "The Slot" or Hayden Flat to Cedar',
        miles: 7,
        activities_am: 'Warm-up, paddle downstream.',
        activities_pm: 'Paddle to takeout, check-out gear, student pick-up.',
      },
    ],
    trip_dates: [
      {
        id: 'td3',
        trip_id: '22222222-2222-2222-2222-222222222222',
        start_date: '2026-06-22',
        end_date: '2026-06-25',
        max_participants: 8,
        current_participants: 2,
        is_available: true,
      },
      {
        id: 'td4',
        trip_id: '22222222-2222-2222-2222-222222222222',
        start_date: '2026-07-13',
        end_date: '2026-07-16',
        max_participants: 8,
        current_participants: 0,
        is_available: true,
      },
    ],
  },
  {
    id: '33333333-3333-3333-3333-333333333333',
    title: 'Adult Paddle Clinic',
    slug: 'adult-paddle-clinic',
    duration: '3 days',
    difficulty: 'Beginner (Class I–II+)',
    age_range: null,
    price: null,
    description:
      'T.R.I.K.S. invites all adults to paddle for three days on the beautiful Trinity River! Paddle together as a group during the day with lunch provided. In the evening, students camp on their own at amazing riverside National Forest Service campgrounds. Build whitewater paddling skills on Class I–II+ rapids while finding stillness through intimate connections with nature.',
    short_description:
      'Three days of paddling on the Trinity River for adults. Build whitewater skills while finding stillness through intimate connections with nature.',
    includes: ['All kayaking gear', 'Professional instruction', 'Lunch daily'],
    location: 'Hayden Flat Campground, Trinity River',
    image_url: '/images/adult-clinic-thumbnail.jpg',
    gallery_urls: [
      '/images/adult-clinic-gallery.jpg',
      '/images/adult-clinic-thumbnail.jpg',
    ],
    video_url: null,
    is_featured: true,
    created_at: '',
    itinerary_days: [
      {
        id: 'ac1',
        trip_id: '33333333-3333-3333-3333-333333333333',
        day_number: 1,
        title: 'Gear Fitting & Flatwater Paddling',
        description: 'Check-in, gear fitting, water comfort, and intro to flatwater paddling at Hayden Flat.',
        river_section: 'Hayden Flat',
        miles: 0,
        activities_am: 'Check-in, paperwork, gear fitting.',
        activities_pm: 'Lunch, water comfort, safety briefing, swimming, wet exit progression, intro paddle & flatwater paddling.',
      },
      {
        id: 'ac2',
        trip_id: '33333333-3333-3333-3333-333333333333',
        day_number: 2,
        title: 'Downstream!',
        description: 'French Creek to Hayden Flat.',
        river_section: 'French Creek to Hayden Flat',
        miles: 4,
        activities_am: 'Flatwater warm-up, paddle downstream.',
        activities_pm: 'Lunch, paddle to Hayden, on-water games.',
      },
      {
        id: 'ac3',
        trip_id: '33333333-3333-3333-3333-333333333333',
        day_number: 3,
        title: 'Downstream!',
        description: 'Big Bar to French Creek.',
        river_section: 'Big Bar to French Creek',
        miles: 5,
        activities_am: 'Flatwater warm-up, paddle downstream.',
        activities_pm: 'Lunch, paddle to take-out.',
      },
    ],
    trip_dates: [
      {
        id: 'td5',
        trip_id: '33333333-3333-3333-3333-333333333333',
        start_date: '2026-07-24',
        end_date: '2026-07-26',
        max_participants: 8,
        current_participants: 1,
        is_available: true,
      },
      {
        id: 'td6',
        trip_id: '33333333-3333-3333-3333-333333333333',
        start_date: '2026-08-07',
        end_date: '2026-08-09',
        max_participants: 8,
        current_participants: 0,
        is_available: true,
      },
    ],
  },
];

export function getFallbackTripBySlug(slug: string): TripWithDetails | null {
  return fallbackTrips.find((t) => t.slug === slug) ?? null;
}

export function getFallbackTripById(id: string): TripWithDetails | null {
  return fallbackTrips.find((t) => t.id === id) ?? null;
}
